//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autoShowClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name brand from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/addCarToXml", ReplyAction="*")]
        autoShowClient.ServiceReference1.addCarToXmlResponse addCarToXml(autoShowClient.ServiceReference1.addCarToXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/addCarToXml", ReplyAction="*")]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.addCarToXmlResponse> addCarToXmlAsync(autoShowClient.ServiceReference1.addCarToXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/showAllCars", ReplyAction="*")]
        void showAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/showAllCars", ReplyAction="*")]
        System.Threading.Tasks.Task showAllCarsAsync();
        
        // CODEGEN: Generating message contract since element name VINNumber from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/searchCarByVin", ReplyAction="*")]
        autoShowClient.ServiceReference1.searchCarByVinResponse searchCarByVin(autoShowClient.ServiceReference1.searchCarByVinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/searchCarByVin", ReplyAction="*")]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.searchCarByVinResponse> searchCarByVinAsync(autoShowClient.ServiceReference1.searchCarByVinRequest request);
        
        // CODEGEN: Generating message contract since element name VINNumber from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/updateCarByVin", ReplyAction="*")]
        autoShowClient.ServiceReference1.updateCarByVinResponse updateCarByVin(autoShowClient.ServiceReference1.updateCarByVinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/updateCarByVin", ReplyAction="*")]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.updateCarByVinResponse> updateCarByVinAsync(autoShowClient.ServiceReference1.updateCarByVinRequest request);
        
        // CODEGEN: Generating message contract since element name VINNumber from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/deleteCarByVin", ReplyAction="*")]
        autoShowClient.ServiceReference1.deleteCarByVinResponse deleteCarByVin(autoShowClient.ServiceReference1.deleteCarByVinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/deleteCarByVin", ReplyAction="*")]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.deleteCarByVinResponse> deleteCarByVinAsync(autoShowClient.ServiceReference1.deleteCarByVinRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/HelloWorld", ReplyAction="*")]
        autoShowClient.ServiceReference1.HelloWorldResponse HelloWorld(autoShowClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(autoShowClient.ServiceReference1.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCarToXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCarToXml", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.addCarToXmlRequestBody Body;
        
        public addCarToXmlRequest() {
        }
        
        public addCarToXmlRequest(autoShowClient.ServiceReference1.addCarToXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class addCarToXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string brand;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int yearOfProduction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VINNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string color;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string transmission;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fuel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public float mileage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public float price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string historicalServiceData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime dateOfRegistration;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string dateOfSale;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string salePrice;
        
        public addCarToXmlRequestBody() {
        }
        
        public addCarToXmlRequestBody(string brand, string model, int yearOfProduction, string VINNumber, string color, string transmission, string fuel, float mileage, float price, string historicalServiceData, System.DateTime dateOfRegistration, string status, string dateOfSale, string salePrice) {
            this.brand = brand;
            this.model = model;
            this.yearOfProduction = yearOfProduction;
            this.VINNumber = VINNumber;
            this.color = color;
            this.transmission = transmission;
            this.fuel = fuel;
            this.mileage = mileage;
            this.price = price;
            this.historicalServiceData = historicalServiceData;
            this.dateOfRegistration = dateOfRegistration;
            this.status = status;
            this.dateOfSale = dateOfSale;
            this.salePrice = salePrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCarToXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCarToXmlResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.addCarToXmlResponseBody Body;
        
        public addCarToXmlResponse() {
        }
        
        public addCarToXmlResponse(autoShowClient.ServiceReference1.addCarToXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addCarToXmlResponseBody {
        
        public addCarToXmlResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCarByVinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchCarByVin", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.searchCarByVinRequestBody Body;
        
        public searchCarByVinRequest() {
        }
        
        public searchCarByVinRequest(autoShowClient.ServiceReference1.searchCarByVinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class searchCarByVinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VINNumber;
        
        public searchCarByVinRequestBody() {
        }
        
        public searchCarByVinRequestBody(string VINNumber) {
            this.VINNumber = VINNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCarByVinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchCarByVinResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.searchCarByVinResponseBody Body;
        
        public searchCarByVinResponse() {
        }
        
        public searchCarByVinResponse(autoShowClient.ServiceReference1.searchCarByVinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class searchCarByVinResponseBody {
        
        public searchCarByVinResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCarByVinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCarByVin", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.updateCarByVinRequestBody Body;
        
        public updateCarByVinRequest() {
        }
        
        public updateCarByVinRequest(autoShowClient.ServiceReference1.updateCarByVinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class updateCarByVinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VINNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newDateofsale;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newSaleprice;
        
        public updateCarByVinRequestBody() {
        }
        
        public updateCarByVinRequestBody(string VINNumber, string newDateofsale, string newSaleprice) {
            this.VINNumber = VINNumber;
            this.newDateofsale = newDateofsale;
            this.newSaleprice = newSaleprice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCarByVinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCarByVinResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.updateCarByVinResponseBody Body;
        
        public updateCarByVinResponse() {
        }
        
        public updateCarByVinResponse(autoShowClient.ServiceReference1.updateCarByVinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateCarByVinResponseBody {
        
        public updateCarByVinResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteCarByVinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteCarByVin", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.deleteCarByVinRequestBody Body;
        
        public deleteCarByVinRequest() {
        }
        
        public deleteCarByVinRequest(autoShowClient.ServiceReference1.deleteCarByVinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class deleteCarByVinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VINNumber;
        
        public deleteCarByVinRequestBody() {
        }
        
        public deleteCarByVinRequestBody(string VINNumber) {
            this.VINNumber = VINNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteCarByVinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteCarByVinResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.deleteCarByVinResponseBody Body;
        
        public deleteCarByVinResponse() {
        }
        
        public deleteCarByVinResponse(autoShowClient.ServiceReference1.deleteCarByVinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteCarByVinResponseBody {
        
        public deleteCarByVinResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(autoShowClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public autoShowClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(autoShowClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : autoShowClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<autoShowClient.ServiceReference1.WebService1Soap>, autoShowClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        autoShowClient.ServiceReference1.addCarToXmlResponse autoShowClient.ServiceReference1.WebService1Soap.addCarToXml(autoShowClient.ServiceReference1.addCarToXmlRequest request) {
            return base.Channel.addCarToXml(request);
        }
        
        public void addCarToXml(string brand, string model, int yearOfProduction, string VINNumber, string color, string transmission, string fuel, float mileage, float price, string historicalServiceData, System.DateTime dateOfRegistration, string status, string dateOfSale, string salePrice) {
            autoShowClient.ServiceReference1.addCarToXmlRequest inValue = new autoShowClient.ServiceReference1.addCarToXmlRequest();
            inValue.Body = new autoShowClient.ServiceReference1.addCarToXmlRequestBody();
            inValue.Body.brand = brand;
            inValue.Body.model = model;
            inValue.Body.yearOfProduction = yearOfProduction;
            inValue.Body.VINNumber = VINNumber;
            inValue.Body.color = color;
            inValue.Body.transmission = transmission;
            inValue.Body.fuel = fuel;
            inValue.Body.mileage = mileage;
            inValue.Body.price = price;
            inValue.Body.historicalServiceData = historicalServiceData;
            inValue.Body.dateOfRegistration = dateOfRegistration;
            inValue.Body.status = status;
            inValue.Body.dateOfSale = dateOfSale;
            inValue.Body.salePrice = salePrice;
            autoShowClient.ServiceReference1.addCarToXmlResponse retVal = ((autoShowClient.ServiceReference1.WebService1Soap)(this)).addCarToXml(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.addCarToXmlResponse> autoShowClient.ServiceReference1.WebService1Soap.addCarToXmlAsync(autoShowClient.ServiceReference1.addCarToXmlRequest request) {
            return base.Channel.addCarToXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<autoShowClient.ServiceReference1.addCarToXmlResponse> addCarToXmlAsync(string brand, string model, int yearOfProduction, string VINNumber, string color, string transmission, string fuel, float mileage, float price, string historicalServiceData, System.DateTime dateOfRegistration, string status, string dateOfSale, string salePrice) {
            autoShowClient.ServiceReference1.addCarToXmlRequest inValue = new autoShowClient.ServiceReference1.addCarToXmlRequest();
            inValue.Body = new autoShowClient.ServiceReference1.addCarToXmlRequestBody();
            inValue.Body.brand = brand;
            inValue.Body.model = model;
            inValue.Body.yearOfProduction = yearOfProduction;
            inValue.Body.VINNumber = VINNumber;
            inValue.Body.color = color;
            inValue.Body.transmission = transmission;
            inValue.Body.fuel = fuel;
            inValue.Body.mileage = mileage;
            inValue.Body.price = price;
            inValue.Body.historicalServiceData = historicalServiceData;
            inValue.Body.dateOfRegistration = dateOfRegistration;
            inValue.Body.status = status;
            inValue.Body.dateOfSale = dateOfSale;
            inValue.Body.salePrice = salePrice;
            return ((autoShowClient.ServiceReference1.WebService1Soap)(this)).addCarToXmlAsync(inValue);
        }
        
        public void showAllCars() {
            base.Channel.showAllCars();
        }
        
        public System.Threading.Tasks.Task showAllCarsAsync() {
            return base.Channel.showAllCarsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        autoShowClient.ServiceReference1.searchCarByVinResponse autoShowClient.ServiceReference1.WebService1Soap.searchCarByVin(autoShowClient.ServiceReference1.searchCarByVinRequest request) {
            return base.Channel.searchCarByVin(request);
        }
        
        public void searchCarByVin(string VINNumber) {
            autoShowClient.ServiceReference1.searchCarByVinRequest inValue = new autoShowClient.ServiceReference1.searchCarByVinRequest();
            inValue.Body = new autoShowClient.ServiceReference1.searchCarByVinRequestBody();
            inValue.Body.VINNumber = VINNumber;
            autoShowClient.ServiceReference1.searchCarByVinResponse retVal = ((autoShowClient.ServiceReference1.WebService1Soap)(this)).searchCarByVin(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.searchCarByVinResponse> autoShowClient.ServiceReference1.WebService1Soap.searchCarByVinAsync(autoShowClient.ServiceReference1.searchCarByVinRequest request) {
            return base.Channel.searchCarByVinAsync(request);
        }
        
        public System.Threading.Tasks.Task<autoShowClient.ServiceReference1.searchCarByVinResponse> searchCarByVinAsync(string VINNumber) {
            autoShowClient.ServiceReference1.searchCarByVinRequest inValue = new autoShowClient.ServiceReference1.searchCarByVinRequest();
            inValue.Body = new autoShowClient.ServiceReference1.searchCarByVinRequestBody();
            inValue.Body.VINNumber = VINNumber;
            return ((autoShowClient.ServiceReference1.WebService1Soap)(this)).searchCarByVinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        autoShowClient.ServiceReference1.updateCarByVinResponse autoShowClient.ServiceReference1.WebService1Soap.updateCarByVin(autoShowClient.ServiceReference1.updateCarByVinRequest request) {
            return base.Channel.updateCarByVin(request);
        }
        
        public void updateCarByVin(string VINNumber, string newDateofsale, string newSaleprice) {
            autoShowClient.ServiceReference1.updateCarByVinRequest inValue = new autoShowClient.ServiceReference1.updateCarByVinRequest();
            inValue.Body = new autoShowClient.ServiceReference1.updateCarByVinRequestBody();
            inValue.Body.VINNumber = VINNumber;
            inValue.Body.newDateofsale = newDateofsale;
            inValue.Body.newSaleprice = newSaleprice;
            autoShowClient.ServiceReference1.updateCarByVinResponse retVal = ((autoShowClient.ServiceReference1.WebService1Soap)(this)).updateCarByVin(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.updateCarByVinResponse> autoShowClient.ServiceReference1.WebService1Soap.updateCarByVinAsync(autoShowClient.ServiceReference1.updateCarByVinRequest request) {
            return base.Channel.updateCarByVinAsync(request);
        }
        
        public System.Threading.Tasks.Task<autoShowClient.ServiceReference1.updateCarByVinResponse> updateCarByVinAsync(string VINNumber, string newDateofsale, string newSaleprice) {
            autoShowClient.ServiceReference1.updateCarByVinRequest inValue = new autoShowClient.ServiceReference1.updateCarByVinRequest();
            inValue.Body = new autoShowClient.ServiceReference1.updateCarByVinRequestBody();
            inValue.Body.VINNumber = VINNumber;
            inValue.Body.newDateofsale = newDateofsale;
            inValue.Body.newSaleprice = newSaleprice;
            return ((autoShowClient.ServiceReference1.WebService1Soap)(this)).updateCarByVinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        autoShowClient.ServiceReference1.deleteCarByVinResponse autoShowClient.ServiceReference1.WebService1Soap.deleteCarByVin(autoShowClient.ServiceReference1.deleteCarByVinRequest request) {
            return base.Channel.deleteCarByVin(request);
        }
        
        public void deleteCarByVin(string VINNumber) {
            autoShowClient.ServiceReference1.deleteCarByVinRequest inValue = new autoShowClient.ServiceReference1.deleteCarByVinRequest();
            inValue.Body = new autoShowClient.ServiceReference1.deleteCarByVinRequestBody();
            inValue.Body.VINNumber = VINNumber;
            autoShowClient.ServiceReference1.deleteCarByVinResponse retVal = ((autoShowClient.ServiceReference1.WebService1Soap)(this)).deleteCarByVin(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.deleteCarByVinResponse> autoShowClient.ServiceReference1.WebService1Soap.deleteCarByVinAsync(autoShowClient.ServiceReference1.deleteCarByVinRequest request) {
            return base.Channel.deleteCarByVinAsync(request);
        }
        
        public System.Threading.Tasks.Task<autoShowClient.ServiceReference1.deleteCarByVinResponse> deleteCarByVinAsync(string VINNumber) {
            autoShowClient.ServiceReference1.deleteCarByVinRequest inValue = new autoShowClient.ServiceReference1.deleteCarByVinRequest();
            inValue.Body = new autoShowClient.ServiceReference1.deleteCarByVinRequestBody();
            inValue.Body.VINNumber = VINNumber;
            return ((autoShowClient.ServiceReference1.WebService1Soap)(this)).deleteCarByVinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        autoShowClient.ServiceReference1.HelloWorldResponse autoShowClient.ServiceReference1.WebService1Soap.HelloWorld(autoShowClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            autoShowClient.ServiceReference1.HelloWorldRequest inValue = new autoShowClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new autoShowClient.ServiceReference1.HelloWorldRequestBody();
            autoShowClient.ServiceReference1.HelloWorldResponse retVal = ((autoShowClient.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<autoShowClient.ServiceReference1.HelloWorldResponse> autoShowClient.ServiceReference1.WebService1Soap.HelloWorldAsync(autoShowClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<autoShowClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            autoShowClient.ServiceReference1.HelloWorldRequest inValue = new autoShowClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new autoShowClient.ServiceReference1.HelloWorldRequestBody();
            return ((autoShowClient.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
    }
}
